#!/bin/bash
if [[ "$1" = "--help" ]] ; then
    exit 0
fi
read sshd_pid </tmp/sshd.pid
if [[ ":${sshd_pid}" != ":" && -d /proc/${sshd_pid} ]] ; then
   kill ${sshd_pid}
   /bin/sleep 2
   if [[ -d /proc/${sshd_pid} ]] ; then
      kill ${sshd_pid}
   fi
fi

