---
defaults: &defaults
  docker:
    - image: cimg/base:stable

version: 2
jobs:
  test:
    <<: *defaults

    steps:
      - checkout
  
      - setup_remote_docker:
          version: 20.10.14
          
      - run:
          name: "Build container"
          command: |
              SDIR=$HOME/sweet
              git clone https://${GH_TOKEN}@github.com/NCAR/sweet.git ${SDIR}
              SVERS=`${SDIR}/sbin/show-git-version -r ${SDIR}`
              if [ ":${SVERS}" = ":" ] ; then
                  echo "unable to determine SWEET version" >&2
                  exit 1
              fi
              echo SWEET_VERSION=$SVERS
              ${SDIR}/docker-build --show --build-arg SWEET_QUALIFIER=:${SVERS}

      - run:
          name: "Run tests"
          command: |
              ./run-all-tests

      - run:
          name: "Verify Doc Generation"
          command: |
              CIRCLE_TAG=0.0.0
              docker create --name docgenerator --entrypoint /usr/local/sweet/sbin/sweet-entrypoint.sh ghcr.io/ncar/sftp-server /usr/local/sweet/bin/gendoc -b $CIRCLE_TAG -w /var/data/wiki -v
              docker start -a docgenerator

  push:
    <<: *defaults

    steps:
      - checkout
          
      - setup_remote_docker:
          version: 20.10.14

      - run:
          name: "Build and Tag Container"
          command: |
              SDIR=$HOME/sweet
              git clone https://${GH_TOKEN}@github.com/NCAR/sweet.git ${SDIR}
              SVERS=`${SDIR}/sbin/show-git-version -r ${SDIR}`
              if [ ":${SVERS}" = ":" ] ; then
                  echo "unable to determine SWEET version" >&2
                  exit 1
              fi
              echo SWEET_VERSION=$SVERS
              ${SDIR}/docker-build --pin-base --version=$CIRCLE_TAG --build-arg SWEET_QUALIFIER=:${SVERS}

      - run:
          name: "Run tests"
          command: |
              ./run-all-tests

      - run:
          name: "Push Container"
          command: |
              echo $GH_TOKEN | docker login ghcr.io -u sweg-ci --password-stdin
              docker push --all-tags ncar/sftp-server

      - run:
          name: "Merge and Push Wiki Documentation"
          command: |
              git config --global user.email "${GH_USER_EMAIL}"
              git config --global user.name "${GH_USER_NAME}"
              REPO=$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
              export REPO
              git clone https://${GH_TOKEN}@github.com/$REPO.wiki.git $HOME/gendocs
              docker create --name docgenerator --entrypoint /usr/local/sweet/sbin/sweet-entrypoint.sh ncar/sftp-server gendoc -b $CIRCLE_TAG -w /var/data/wiki -v
              docker cp $HOME/gendocs/. docgenerator:/var/data/wiki
              docker start -a docgenerator
              docker cp docgenerator:/usr/local/sftp-server/gendoc/. $HOME/gendocs
              cd $HOME/gendocs
              git add .
              if git commit -m "Doc build for $CIRCLE_TAG" ; then
                  git push
              fi

workflows:
  version: 2
  test-push:
    jobs:
      - test:
          context: sweg
      - push:
          context: sweg
          filters:
            tags:
              only: /^\d+\.\d+\.\d+([-+].*)?$/
            branches:
              ignore: /.*/
