---
defaults: &defaults
  docker:
    - image: docker:stable-git

version: 2
jobs:
  test:
    <<: *defaults

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: "Build container"
          command: |
              set +e
              SDIR=$HOME/sweet
              git clone https://${GH_TOKEN}@github.com/NCAR/sweet.git ${SDIR}
              SVERS=`$SDIR/sbin/show-git-version -r`
              ${SDIR}/docker-build --show --build-arg SWEET_QUALIFIER=:${SVERS}

      - run:
          name: "Run tests"
          command: |
              cd sbin
              ./run-test-server --wait=30
              ./run-test-client tbin/run-sftp-tests

      - run:
          name: "Verify Doc Generation"
          command: |
              set +e
              CIRCLE_TAG=0.0.0
              git config --global user.email "${GH_USER_EMAIL}"
              git config --global user.name "${GH_USER_NAME}"
              REPO=$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
              export REPO
              git clone https://${GH_TOKEN}@github.com/$REPO.wiki.git $HOME/gendocs
              docker create --name docgenerator --entrypoint /usr/local/sweet/sbin/sweet-entrypoint.sh ncar/sftp-server gendoc -b $CIRCLE_TAG -w /var/data/wiki -v
              docker cp $HOME/gendocs/. docgenerator:/var/data/wiki
              docker start -a docgenerator
              docker cp docgenerator:/usr/local/sftp-server/gendoc/. $HOME/gendocs
              cd $HOME/gendocs
              git add .
              git commit -m 'Latest doc build'

  push:
    <<: *defaults

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: "Build and Tag Container"
          command: |
              SDIR=$HOME/sweet
              git clone https://${GH_TOKEN}@github.com/NCAR/sweet.git ${SDIR}
              SVERS=`$SDIR/sbin/show-git-version -r`
              ${SDIR}/docker-build --pin-base --version=$CIRCLE_TAG --build-arg SWEET_QUALIFIER=:${SVERS}

      - run:
          name: "Run tests"
          command: |
              cd sbin
              ./run-test-server --wait=30
              ./run-test-client tbin/run-sftp-tests

      - run:
          name: "Push Container"
          command: |
              printenv | sed -n -e 's/DOCKERHUB_PASSWORD=\(.*\)/\1/p' | docker login --username $DOCKERHUB_USERNAME --password-stdin
              docker push ncar/sftp-server

      - run:
          name: "Merge and Push Wiki Documentation"
          command: |
              git config --global user.email "${GH_USER_EMAIL}"
              git config --global user.name "${GH_USER_NAME}"
              REPO=$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
              export REPO
              git clone https://${GH_TOKEN}@github.com/$REPO.wiki.git $HOME/gendocs
              docker create --name docgenerator --entrypoint /usr/local/sweet/sbin/sweet-entrypoint.sh ncar/sftp-server gendoc -w /var/data/wiki -v
              docker cp $HOME/gendocs/. docgenerator:/var/data/wiki
              docker start -a docgenerator
              docker cp docgenerator:/usr/local/sftp-server/gendoc/. $HOME/gendocs
              cd $HOME/gendocs
              git add .
              if git commit -m 'Latest doc build' ; then
                  git push
              fi

workflows:
  version: 2
  test-push:
    jobs:
      - test:
          context: sweg
      - push:
          context: sweg
          filters:
            tags:
              only: /^\d+\.\d+\.\d+([-+].*)?$/
            branches:
              ignore: /.*/
