---
defaults: &defaults
  docker:
    - image: circleci/golang:buster

version: 2
jobs:
  test:
    <<: *defaults

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: "Build container and run environment"
          command: |
              set +e
              git clone https://${GH_TOKEN}@github.com/NCAR/sweet.git $HOME/sweet
              $HOME/sweet/docker-build
              mkdir $HOME/secrets
              chmod 1777 $HOME/secrets
              ls -l $HOME
              docker images

      - run:
          name: "Create SSH key pairs"
          command: |
              cd test
              docker-compose --env-file ./circleci.env run reset-client-keys
              docker-compose --env-file ./circleci.env run reset-server-keys
              ls -lR $HOME/secrets
              
workflows:
  version: 2
  test-push:
    jobs:
      - test:
          context: sweg
