---
defaults: &defaults
  docker:
    - image: docker:stable-git

version: 2
jobs:
  test:
    <<: *defaults

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: "Build container"
          command: |
              set +e
              git clone https://${GH_TOKEN}@github.com/NCAR/sweet.git $HOME/sweet
              $HOME/sweet/docker-build --show

      - run:
          name: "Run tests"
          command: |
              set +ex
              cd sbin
              nohup ./run-test-server </dev/null >../../test-server.log 2>&1 &
              for i in 1 2 2 3 5 8 13 21 ; do
                  if grep -q 'Server listening ' ../../test-server.log ; then
                      echo server is up
                      break
                  fi
                  sleep $i
              done
              cat ../../test-server.log
              ./run-test-client
              exit 0


workflows:
  version: 2
  test-push:
    jobs:
      - test:
          context: sweg
