---
defaults: &defaults
  docker:
    - image: docker:stable-git

version: 2
jobs:
  test:
    <<: *defaults

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: "Build container"
          command: |
              set +e
              git clone https://${GH_TOKEN}@github.com/NCAR/sweet.git $HOME/sweet
              $HOME/sweet/docker-build --show

      - run:
          name: "Run tests"
          command: |
              set +e
              cd sbin
              ./run-test-server
              docker ps
              docker network ls
              ./run-test-client
              exit 0


workflows:
  version: 2
  test-push:
    jobs:
      - test:
          context: sweg
