#!/bin/sh
PROG=cleanup-test-server
DESC="Stop and clean up the container created using run-test-server"
USAGE1="$PROG containername"
USAGE2="$PROG -h|--help"
USAGE="Usage:
    $USAGE1
    $USAGE2"

DEFAULT_CONT=testsftp

HELP_TEXT="
        Clean up a SFTP server container and its network. The argument is the
        server container name.
"

SCRIPTDIR=`cd \`dirname $0\`; pwd`

case $1 in
     -h|--help)
         cat <<EOF
NAME            
        $PROG - $DESC

SYNOPSIS
        $USAGE1
        $USAGE2

DESCRIPTION$HELP_TEXT
EOF
         exit 1 ;;
            
     -*)
         echo "$PROG: invalid option: $arg" >&2
         echo "$USAGE" >&2
         exit 1 ;;

     '')
         SFTP_CONT=$DEFAULT_CONT ;;

     *)
         SFTP_CONT="$1" ;;
esac

id=`docker ps --filter "name=${SFTP_CONT}" -q`
if [ ":$id" != ':' ] ; then
    echo "Killing container \"$SFTP_CONT\""
    docker kill ${SFTP_CONT}
fi

id=`docker ps -a --filter "name=${SFTP_CONT}" -q`
if [ ":$id" != ':' ] ; then
    echo "Removing container \"$SFTP_CONT\""
    docker rm -f ${SFTP_CONT}
fi
netinfo=`docker network inspect ${SFTP_CONT}_net 2>/dev/null`
if [ ":$netinfo" != ":[]" ] ; then
    echo "Removing network \"${SFTP_CONT}_net\""
    docker network rm ${SFTP_CONT}_net
fi
