#!/bin/sh
PROG=run-test-server
DESC="Start a test SFTP server container with temporary keys"
USAGE1="$PROG [-u|--user=user:grp] [-s|--server=svcont] [-n|--network=network]
                 [-i|--image=clientimage]"
USAGE2="$PROG [-h|--help]"
USAGE="Usage:
    $USAGE1
    $USAGE2"

DEFAULT_CONT=testsftp
DEFAULT_USER=sweetuser:sftp

HELP_TEXT="
        Configure and start a test SFTP container with generated server- and
        client-side keys.

        The SFTP container is always assigned a name. The name can be given
        on the command line, but if it is not, \"$DEFAULT_CONT\" is used.
        The container will run detached. Use \"docker logs <name>\"
        to view logs. Use \"docker kill <name>\" to stop/remove the server
        container.

        A client container can access the generated keys if the
        \"--volumes-from <containername>\" argument is included in the
        \"docker run\" command. Specifically, the volumes shared from
        the server container include \"/run/secrets\" (which contains shared
        keys), \"/mnt\" (which is the volume that SFTP will serve), and
        \"/var/data\" (which is not used by the sftp server, but is ofter used
        by other containers). Note that since \"/mnt\" is shared, a client can
        bypass the SFTP interface to either seed the data that can be
        downloaded or verify data that is uploaded. See \"run-test-client\".

        This script intentionally shuns volume mounts and docker-compose.
        It is designed for testing in remote CI environments (CircleCI in
        particular) and for use by external packages.

        The following flags are supported:

        -u|--user=user:grp
            If given, the username:groupname or uid:gid that the client will
            use. Default is $DEFAULT_USER.

        -s|--server=svcont
            The name to assign to the SFTP server container; if not given,
            \"${DEFAULT_CONT}\" is used.

        -n|--network=network
            The name of the network to use. Default is \"<container>_net\".

        -i|--image=clientimage
            The name of the docker image that will be used for the client
            container. The image must either be based on \"ncar/sftp-server\",
            or be based on \"ncar/sweet\" and have \"ncar/sftp-server\" scripts
            installed under \"/usr/local/sftp-server\". Default is
            \"ncar/sftp-server\"

        -w|--wait=secs
            Do not return until the server container is listening for
            connections or the number of secons have elapsed; in the later
            case, kill the container and return an error.

        -h|--help
            Display help text and exit.
"

SFTP_CONT=$DEFAULT_CONT
USER_ARG=$DEFAULT_USER
NETWORK=
SFTP_PORT=2222
CLIENT_IMAGE=ncar/sftp-server
CLIENT_PACKAGE=
WAIT=
TMPLOG=/tmp/run-test-server.$$.log
ENTRYPOINT_DEBUG=${ENTRYPOINT_DEBUG:-0}

main () {
    processCommandLine "$@" || return 1

    trap "rm -f ${TMPLOG} ; exit 255" 1 2 13 15

    CLIENT_PACKAGE=`verifyClientImage ${CLIENT_IMAGE}` || return 1
    
    setupNetwork ${NETWORK} || return

    removeExistingContainer ${SFTP_CONT} || return 1
    
    createStoppedSftpContainer ${SFTP_CONT} ${NETWORK} || return 1

    createKeyPairsUnderMnt ${SFTP_CONT} ${USER_ARG} || return 1

    moveKeyPairsToSecrets ${SFTP_CONT} || return 1

    echo "Starting container \"${SFTP_CONT}\""

    if [ ":$WAIT" != ":" ] ; then
        currtime=`date +%s`
        endtime=`expr ${currtime} + ${WAIT}`
        nohup docker start -a ${SFTP_CONT} </dev/null >${TMPLOG} 2>&1 &
        rc=0
        while true ; do
            if grep -q 'Server listening ' ${TMPLOG} ; then
                break
            fi
            currtime=`date +%s`
            if [ "${currtime}" -gt "${endtime}" ] ; then
                rc=1
                break
            fi
        done
        cat ${TMPLOG}
        rm -f "${TMPLOG}"

    else
        docker start -a ${SFTP_CONT}
        rc=$?
    fi

    return $rc
}

verifyClientImage () {
    image="$1"
    sftp=`expr "${image}:" : '(ncar/sftp-server)[:@].*'`
    if [ ":${sftp}" = ":ncar/sftp-server" ] ; then
        return "sftp-server"
    fi
    package=`docker run --rm --entrypoint /bin/cat ${image} /etc/parmdb-init/PACKAGE 2>/dev/null`
    if [ ":${package}" = ":" ] ; then
        echo "$PROG: client image is not based on ncar/sweet" >&2
        exit 1
    fi
    sftpdir=`docker run --rm --entrypoint /bin/ls ${image} -ld /usr/local/sftp-server 2>/dev/null`
    if [ ":${sftpdir}" = ":" ] ; then
        echo "$PROG: client image does not include sftp-server scripts" >&2
        exit 1
    fi
    echo $package
}

setupNetwork () {
    network="$1"
    netinfo=`docker network inspect ${network} 2>/dev/null`
    if [ ":$netinfo" = ":[]" ] ; then
        echo "Creating network \"${network}\"..."
        docker network create --driver bridge ${network} || return 1
    fi
    return 0
}

removeExistingContainer () {
    container="$1"
    id=`docker ps --filter "name=${container}" -q`
    if [ ":$id" != ':' ] ; then
        echo "Stopping existing container \"$container\""
        docker kill ${container}
    fi
    id=`docker ps -a --filter "name=${container}" -q`
    if [ ":$id" != ':' ] ; then
        echo "Removing existing container \"$container\""
        docker rm -f ${container}
    fi
}

createStoppedSftpContainer () {
    container="$1"
    network="$2"

    trap "rm -f ${TMPLOG} ; docker rm -f ${container} >/dev/null 2>&1 ; exit 255" 1 2 13 15
    echo "Creating stopped container \"$container\""
    docker create --rm --name ${container} \
           -v /run/secrets -v /mnt -v /var/data \
           --network ${network} \
           --tmpfs /tmp:rw,noexec,nosuid \
           -e "SERVICE=server" \
           -e "CLIENT_PACKAGE=${CLIENT_PACKAGE}" \
           -e "RUN_ENV=test" \
           -e "ENTRYPOINT_DEBUG=${ENTRYPOINT_DEBUG}" \
           ncar/sftp-server:latest \
           /usr/sbin/sshd -D -e -p $SFTP_PORT

    set : `docker inspect -f '{{range $key, $value := .NetworkSettings.Networks}}{{$key}} {{end}}' ${container}`
    net="$2"
    if [ ":${net}" != ":${NETWORK}" ] ; then
        echo "$PROG: unable to attach to network \"${NETWORK}\" (using \"${net}\")" >&2
        return 1
    fi
    echo "Using network \"${net}\""

    echo "Initializing volume directories"
    docker run --rm \
           --volumes-from ${container} \
           debian:buster-slim \
           /bin/bash -c 'mkdir -p /var/data /mnt /run/secrets ; chmod 1777 /var/data /mnt'
}

createKeyPairsUnderMnt () {
    container="$1"
    usergrp="$2"

    echo "Creating client keys as ${usergrp}"
    docker run --rm \
       --volumes-from ${container} \
       -u ${usergrp} \
       -e "PACKAGE=${CLIENT_PACKAGE}" \
       -e "SERVICE=client" \
       -e "RUN_ENV=test" \
       --entrypoint /usr/local/sweet/sbin/sweet-entrypoint.sh \
       ${CLIENT_IMAGE} \
       /usr/local/sftp-server/sbin/ssh-keysync || return 1

    echo "Creating server keys as sftp:sftp"
    docker run --rm \
           --volumes-from ${container} \
           -e "SERVICE=server" \
           -e "RUN_ENV=test" \
           --tmpfs /tmp:rw,noexec,nosuid \
           --entrypoint /usr/local/sweet/sbin/sweet-entrypoint.sh \
           ncar/sftp-server:latest \
           /usr/local/sftp-server/sbin/ssh-keysync || return 1
}

moveKeyPairsToSecrets () {
    container="$1"

    echo "Installing keys"
    docker run --rm \
           --volumes-from ${container} \
           debian:buster-slim \
           /bin/bash -c 'mv /mnt/* /run/secrets'
}


processCommandLine () {
    while [ $# != 0 ] ; do
        arg="$1"
        shift
        case $arg in
            -h|--help)
                cat <<EOF
NAME            
        $PROG - $DESC

SYNOPSIS
        $USAGE1
        $USAGE2
        $USAGE3

DESCRIPTION$HELP_TEXT
EOF
                return 1 ;;

            -[usniw]?*)
                opt=`expr "${arg}" : '\(-.\).*'`
                rest=`expr "${arg}" : '-.\(.*\)'`
                set : ${opt} "${rest}" "$@"
                shift ;;

            --*=*)
                opt=`expr "${arg}" : '\(--[^=]*\)=.*'`
                rest=`expr "${arg}" : '--[^=]*=\(.*\)'`
                set : ${opt} "${rest}" "$@"
                shift ;;
            
            -u|--user)
                USER_ARG="$1"
                shift ;;
            
            -s|--server)
                SFTP_CONT="$1"
                shift ;;
            
            -n|--network)
                NETWORK="$1"
                shift ;;
            
            -i|--image)
                CLIENT_IMAGE="$1"
                shift ;;
            
            -w|--wait)
                WAIT=`expr "$1" : '\([0-9][0-9]*\)$'`
                if [ ":${WAIT}" = ":" ] ; then
                    echo "$PROG: invalid -w|--wait value: \"$1\"" >&2
                    exit 1
                fi
                shift ;;
            
            -*)
                echo "$PROG: invalid option: $arg" >&2
                echo "$USAGE" >&2
                return 1 ;;
            
            *)
                echo "$PROG: unexpected arguments: $arg $@" >&2
                echo "$USAGE" >&2
                return 1 ;;
        esac
    done
    if [ ":${NETWORK}" = ":" ] ; then
        NETWORK="${SFTP_CONT}_net"
    fi

    return 0

}

main "$@"
