#!/bin/sh
PROG=run-test-client
DESC="Run a client container counterpart to the run-test-server container"
USAGE1="$PROG [-u|--user=uid:gid] [-s|--server=svcont]"
USAGE2="$PROG -h|--help"
USAGE="Usage:
    $USAGE1
    $USAGE2"

DEFAULT_CONT=testsftp
DEFAULT_USER=sweetuser:sftp

HELP_TEXT="
        Start a test SFTP client container that connects to a container
        started using run-test-server and runs the \"NCAR/sftp-server\" test
        suite.

        This script is intentionally simple to act as a guide to writing other
        client test scripts.

        The following arguments are supported:

        -h|--help
            Display help text and exit.

        -u|--user=user:group
            If given, the username:groupname or uid:gid that the client will
            use. Default is $DEFAULT_USER. This must match the corresponding
            argument passed to \"run-test-server\".

        -s|--server=name
            The name to assign to the SFTP server container; if not given,
            \"${DEFAULT_CONT}\" is used. This must match the corresponding
            argument passed to \"run-test-server\".

        -n|--network=network
            The name of the network to use. Default is \"<container>_net\".
"

SCRIPTDIR=`cd \`dirname $0\`; pwd`

SFTP_CONT=$DEFAULT_CONT
USER_ARG=$DEFAULT_USER
INTERACTIVE=0
NETWORK=
SFTP_PORT=2222

main () {
    processCommandLine "$@" || return 1

    checkNetwork "${NETWORK}" || return 1
    
    checkServerContainer "${SFTP_CONT}" "${NETWORK}" || return 1

    runTests "${USER_ARG}" "${SFTP_CONT}" "${NETWORK}" || return 1

    return 0
}

checkNetwork () {
    network="$1"
    netinfo=`docker network inspect ${network} 2>/dev/null`
    if [ ":$netinfo" = ":[]" ] ; then
        echo "$PROG: \"${network}\": no such network" >&2
        exit 1
    fi
    return 0
}


checkServerContainer () {
    container="$1"
    network="$2"
    echo "Checking for container \"$container\""
    id=`docker ps --filter "name=${container}" -q`
    if [ ":$id" = ':' ] ; then
        echo "$PROG: $container: no such container" >&2
        return 1
    fi
    set : `docker inspect -f '{{range $key, $value := .NetworkSettings.Networks}}{{$key}} {{end}}' ${container}`
    svnet="$2"
    if [ ":${svnet}" != ":${network}" ] ; then
        echo "$PROG: server uses network \"${svnet}\", not \"${network}\"" >&2
        return 1
    fi
    
    return 0
}

runTests () {
    userArg="$1"
    container="$2"
    network="$3"

    echo "Creating test client for server container \"$container\"..."
    docker create --rm --name ${container}_cl \
           --network ${network} \
           --volumes-from ${container} \
           --tmpfs /tmp:rw,noexec,nosuid \
           -u ${userArg} \
           -e "SERVICE=client" \
           -e "RUN_ENV=test" \
           -e "SFTP_SERVER=${container}" \
           -e "SFTP_PORT=${SFTP_PORT}" \
           -e "INTERACTIVE=0" \
           -e "ENTRYPOINT_DEBUG=0" \
           --entrypoint /usr/local/sweet/sbin/sweet-entrypoint.sh \
           ncar/sftp-server:latest \
           --source=/usr/local/sftp-server/sbin/sftp-cl-entrypoint.rc \
           /usr/local/sftp-server/tbin/sftp-client-shell
    set : `docker inspect -f '{{range $key, $value := .NetworkSettings.Networks}}{{$key}} {{end}}' ${container}_cl`
    clnet="$2"
    echo "Using network \"${clnet}\""

    echo "Starting container \"${container}_cl\"..."
    docker start -a ${container}_cl
}


processCommandLine () {
    while [ $# != 0 ] ; do
        arg="$1"
        shift
        case $arg in
            -h|--help)
                cat <<EOF
NAME            
        $PROG - $DESC

SYNOPSIS
        $USAGE1
        $USAGE2
        $USAGE3

DESCRIPTION$HELP_TEXT
EOF
                return 1 ;;

            -[nus]?*)
                opt=`expr "${arg}" : '\(-.\).*'`
                rest=`expr "${arg}" : '-.\(.*\)'`
                set : ${opt} "${rest}" "$@"
                shift ;;

            --*=*)
                opt=`expr "${arg}" : '\(--[^=]*\)=.*'`
                rest=`expr "${arg}" : '--[^=]*=\(.*\)'`
                set : ${opt} "${rest}" "$@"
                shift ;;
            
            -u|--user)
                USER_ARG="$1"
                shift ;;
            
            -s|--server)
                SFTP_CONT="$1"
                shift ;;
            
            -n|--network)
                NETWORK="$1"
                shift ;;
            
            -*)
                echo "$PROG: invalid option: $arg" >&2
                echo "$USAGE" >&2
                return 1 ;;
            
            *)
                echo "$PROG: invalid arguments: $arg $@" >&2
                echo "$USAGE" >&2
                return 1 ;;
        esac
    done
    if [ ":${NETWORK}" = ":" ] ; then
        NETWORK="${SFTP_CONT}_net"
    fi

    return 0

}

main "$@"


