#!/bin/sh
PROG=sftp-server-wrapper
DESC="Wrapper for /usr/lib/openssh/sftp-server"
USAGE1="$PROG sftp-server_args"
USAGE2="$PROG -h|--help"
HELP_TEXT="
        This script exec's /usr/lib/openssh/sftp-server, possibly with
        additional arguments.
"
ENV_HELP="
        DENY_REQUESTS
            A comma-separated list of SFTP protocol commands that will be
            denied by the server.

        LOG_LEVEL
            The log level. Possible valuies are QUIET, FATAL, ERROR, INFO,
            VERBOSE, DEBUG, DEBUG1, DEBUG2, and DEBUG3.

        READONLY
            If set to a \"truthy\" value, the server will be started in
            read-only mode.
"
case $1 in
    -h|--help)
        cat <<EOF
NAME
        $PROG - $DESC

SYNOPSIS
        $USAGE1
        $USAGE2

DESCRIPTION$HELP_TEXT
EOF
        exit 0 ;;
esac

if [ ":$DENY_REQUESTS" != ":" ] ; then
   set : -P ${DENY_REQUESTS} "$@"
   shift
fi
if [ ":$LOG_LEVEL" != ":" ] ; then
   set : -l ${LOG_LEVEL} "$@"
   shift
fi
if truthy "${READONLY}" ; then
   set : -R "$@"
   shift
fi
echo "Sleeping 5" >&2
sleep 5
echo "Exec-ing /usr/lib/openssh/sftp-server -e $@..." >&2
exec /usr/lib/openssh/sftp-server -e "$@"


