#!/bin/sh
PROG=run-sftp-tests
if [ ":$1" = ":--help" ] ; then
    exit 0
fi

if [ ":${SFTP_SERVER}" = ":" ] ; then
    echo "$PROG: SFTP_SERVER is not set" >&2
    exit 1
fi
if [ ":${SFTP_PORT}" = ":" ] ; then
    SFTP_PORT=22
fi
SCRIPTDIR=`cd \`dirname $0\`; pwd`
cd ${SCRIPTDIR}
echo "Running tests..."
runtests
rc=$?

echo "Shutting down ${SFTP_SERVER}:${SFTP_PORT}..."
ssh -i $ID_RSA -p ${SFTP_PORT} ${SFTPUSER}@${SFTP_SERVER} shutdown

exit $rc
