#!/bin/sh
if [ ":$1" = ":--help" ] ; then
    exit 0
fi

SCRIPTDIR=`cd \`dirname $0\`; pwd`
cd ${SCRIPTDIR}
echo "Running tests..."
runtests
rc=$?

echo "Shutting down ${SFTP_SERVER}:${SFTP_PORT}..."
ssh -i $ID_RSA -p ${SFTP_PORT} ${SFTP_USER}@${SFTP_SERVER} shutdown

exit $rc
