#!/bin/bash
PROG=sftp-client-shell
DESC="Script for testing sftp-server"
USAGE1="$PROG [-h|--help]"
HELP_TEXT="
        This script is meant to be run as the main command in a container
        that tests connectivity to a \"sftp-server\" container.
 
        The container must source \"sftp-cl-entrypoint.rc\" as part of its
        ENTRYPOINT, and the SFTP_SERVER environment variable must be set to
        the name of the sftp server host/container.

        If arguments are provided, they are assumed to specify a shell command
        to run in the container. If no arguments are provided and the
        INTERACTIVE environment variable has a \"truthy\" value, this script
        will enter an infinite sleep loop with the expectation that someone
        will \"docker exec\" into the container. If no arguments are provided
        and \$INTERACTIVE is not truthy, the script will run all test scripts
        in ${PACKAGE_DIR}/tbin then exit.
"
HELP_ENVIRONMENT="
        SFTP_SERVER
            The name/address of the SFTP server. Required.

        SFTP_PORT
            The SFTP network port. If not defined, 22 is used.
"

case $1 in
    -h|--help)
        cat <<EOF
NAME
        $PROG - $DESC

SYNOPSIS
        $USAGE1

DESCRIPTION$HELP_TEXT
EOF
        exit 0 ;;
esac
if [ ":${SFTP_SERVER}" = ":" ] ; then
    echo "$PROG: SFTP_SERVER environment variable is not set" >&2
    exit 1
fi
SFTP_PORT=${SFTP_PORT:-22}

SERVER="${SFTP_SERVER}:${SFTP_PORT}"

echo "Waiting for \"${SERVER}\"..."
check-server --wait=60 ${SERVER}
rc=$?
if [ $rc = 0 ] ; then
    echo "\"${SERVER}\" is ready" >&2
elif [ $rc = 1 ] ; then
    echo "\"${SERVER}\" timed out" >&2
    exit 1
else
    exit 1
fi

if truthy "${INTERACTIVE}" ; then
    echo "Waiting indefinitely (use 'docker exec')..." >&2
    while true ; do
        sleep 60 ;
    done
    exit 0
fi
cd ${PACKAGE_DIR}/tbin || exit
runtests
rc=$?
ssh -i $ID_RSA -p $SFTP_PORT sftp@$SFTP_SERVER shutdown

exit $rc
